### ISSUE TITLE
Question: Future release management of this repo?

### ISSUE THREAD

**Issue by brettswift** [aws-quickstart/quickstart-microsoft-utilities#14]
First off - thanks for this quickstart - and one that consumes this - the windows / jenkins CICD quickstart. 

We would like to use these scripts but need to source them locally.  I'm interested in contributing fixes or changes to this github repository.   However for continuity we require to have these deployed locally as an artifact.

Is there a possibility that this repository could start using a tagged release process?  This way I would be able to mirror the tags locally and leverage the code as a dependency, rather than supporting these scripts privately and outside of the open source community.

I hope this makes sense.. I'd be happy to clarify! 

Thanks! 

(ps I guess the same question would be applicable to other quickstarts).

**Comment by virtlima** [comment]
Brettswift, 

I apologize for the late reply, is this something you would like us to consider doing on this repo still?

**Comment by brettswift** [comment]
I don't use this anymore. Thanks though

**Comment by virtlima** [comment]
Okay, if you have any ideas or anything we can do to make things easier please lets us know.
